wbb_sonata:
    resource: "@WBBCoreBundle/Resources/config/routing/sonata.yml"
    prefix:   /

get_suburbs_from_city:
    pattern: /ajax/get-suburbs-from-city/{bar}/{cityId}/{suburbId}
    defaults: {_controller: WBBCoreBundle:Admin\Ajax\Ajax:getSuburbsFromCity, bar: 0, suburbId: 0}
    options:
        expose: true
