wbb_sonata:
    resource: "@WBBCoreBundle/Resources/config/routing/sonata.yml"
    prefix:   /

get_suburbs_from_city:
    pattern: /ajax/get-suburbs-from-city/{bar}/{cityId}/{suburbId}
    defaults: {_controller: WBBCoreBundle:Ajax\Ajax:getSuburbsFromCity, bar: 0, suburbId: 0}
    options:
        expose: true

get_cities_from_country:
    pattern: /ajax/get-cities-from-country/{bestof}/{countryId}/{cityId}
    defaults: {_controller: WBBCoreBundle:Ajax\Ajax:getCitiesFromCountry, bestof: 0, cityId: 0}
    options:
        expose: true

get_medias_from_bar:
    pattern: /ajax/get-medias-from-bar/{barID}/{mediaID}
    defaults: {_controller: WBBCoreBundle:Ajax\Ajax:getBarMedias, barID: 0, mediaID: 0}
    options:
        expose: true

wbb_cities_poi:
    pattern: /poi/{cityID}/{suburbID}
    defaults: { _controller: WBBCoreBundle:Ajax\Ajax:poiList, cityID: 0, suburbID: 0}
    options:
        expose: true

wbb_cities_list:
    pattern: /list/cities
    defaults: { _controller: WBBCoreBundle:Ajax\Ajax:citiesList }
    options:
        expose: true

wbb_cities:
    pattern: /cities
    defaults: { _controller: WBBCoreBundle:City:cities }