#Gaufrette config
knp_gaufrette:
    adapters:
        bar_adapter:
            aws_s3:
                service_id:   amazon_storage
                bucket_name:    %aws_s3_bucket%
                options:
                    directory:  uploads/bars

        city_adapter:
            aws_s3:
                service_id:   amazon_storage
                bucket_name:    %aws_s3_bucket%
                options:
                    directory:  uploads/cities

        news_adapter:
            aws_s3:
                service_id:   amazon_storage
                bucket_name:    %aws_s3_bucket%
                options:
                    directory:  uploads/news

        bestof_adapter:
            aws_s3:
                service_id:   amazon_storage
                bucket_name:    %aws_s3_bucket%
                options:
                    directory:  uploads/bestofs

        avatar_adapter:
            aws_s3:
                service_id:   amazon_storage
                bucket_name:    %aws_s3_bucket%
                options:
                    directory:  uploads/avatars

        ads_adapter:
            aws_s3:
                service_id:   amazon_storage
                bucket_name:    %aws_s3_bucket%
                options:
                    directory:  uploads/ads

        sponsor_adapter:
            aws_s3:
                service_id:   amazon_storage
                bucket_name:    %aws_s3_bucket%
                options:
                    directory:  uploads/sponsors

    filesystems:

        bars_fs:
            adapter: bar_adapter

        news_fs:
            adapter: news_adapter

        bestofs_fs:
            adapter: bestof_adapter

        avatars_fs:
            adapter: avatar_adapter

        ads_fs:
            adapter: ads_adapter

        sponsors_fs:
            adapter: sponsor_adapter

        cities_fs:
            adapter: city_adapter

    stream_wrapper: ~