#Sonata Media Bundle
sonata_media:
    default_context: bar
    db_driver: doctrine_orm
    contexts: #Add default context
        bar:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                preview : { width: 100 , height: 100, quality: 100 }
                286_210 : { width: 286 , height: 210, quality: 100 }
                285_215 : { width: 285 , height: 215, quality: 100 }
                425_320 : { width: 425 , height: 320, quality: 100 }
                640_480 : { width: 640 , height: 480, quality: 100 }
        news:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                preview : { width: 100 , height: 100, quality: 100 }
                286_210 : { width: 286 , height: 210, quality: 100 }
                385_278 : { width: 385 , height: 278, quality: 100 }
                425_320 : { width: 425 , height: 320, quality: 100 }
                770_578 : { width: 770 , height: 578, quality: 100 }

        city:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview : { width: 100 , height: 100, quality: 100 }
                170_175 : { width: 170 , height: 175, quality: 100 }

        bestof:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview : { width: 100 , height: 100, quality: 100 }
                370_278 : { width: 370 , height: 278, quality: 100 }
                285_215 : { width: 285 , height: 215, quality: 100 }
                384_280 : { width: 384 , height: 280, quality: 100 }

        ads:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview :   { width: 100 , height: 100, quality: 100 }
                300_250 :   { width: 300 , height: 250, quality: 100 }
                300_600 :   { width: 300 , height: 600, quality: 100 }
                728_90  :   { width: 728 , height: 90, quality: 100 }

        sponsor:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview : { width: 100 , height: 100, quality: 100 }
                82_82   : { width:  82 , height:  82, quality: 100 }
                368_168 : { width: 368 , height: 168, quality: 100 }

        avatar:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                preview :   { width: 100, height: 100, quality: 100}
                82_82   :   { width:  82, height:  82, quality: 100}
                145_145 :   { width: 145, height: 145, quality: 100}

    cdn:
        server:
#            path: /uploads/media
            path: http://wbb-bucket.s3-website-us-east-1.amazonaws.com #http://staging.worldsbestbars.com.s3-website-eu-west-1.amazonaws.com

    filesystem:
#        local:
#            directory:  %kernel.root_dir%/../web/uploads/media
#            create:     true
        s3:
            bucket: wbb-bucket
            accessKey: AKIAJ6WSWPZUXSICYDPQ #AKIAJM6ZSVZZ3WLRHZIA
            secretKey: 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 #Sw9IbIoSTjfQIamFAFWqljY/tNhQmDBnChYzSC9T
            create: true
#            region:         s3-website-us-east-1.amazonaws.com #s3-website-eu-west-1.amazonaws.com # change if not using US Standard region
#            storage: standard # can be one of: standard or reduced
#            acl: public # can be one of: public, private, open, auth_read, owner_read, owner_full_control
#            encryption:     aes256 # can be aes256 or not set
#            cache_control:  max-age=86400 # or any other
#            meta:
#                key1:       value1 #any amount of metas(s ent as x-amz-meta-key1 = value1)

    providers:
        image:
            filesystem: sonata.media.filesystem.s3
            resizer: sonata.media.resizer.custom #sonata.media.resizer.custom
            cdn: sonata.media.cdn.server
            allowed_extensions: ['jpg', 'png', 'jpeg']
            allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']