vich_uploader:
    db_driver: orm
    gaufrette: true
    storage:   vich_uploader.storage.gaufrette
    mappings:

        city_image:
            uri_prefix:         /images/cities
            upload_destination: cities_fs
            namer: vich_uploader.namer_origname

        bar_image:
            uri_prefix:         /images/bars
            upload_destination: bars_fs
            namer: vich_uploader.namer_origname

        bestof_image:
            uri_prefix:         /images/bestofs
            upload_destination: bestofs_fs
            namer: vich_uploader.namer_origname

        news_image:
            uri_prefix:         /images/news
            upload_destination: news_fs
            namer: vich_uploader.namer_origname

        ads_image:
            uri_prefix:         /images/ads
            upload_destination: ads_fs
            namer: vich_uploader.namer_origname

        sponsor_image:
            uri_prefix:         /images/sponsors
            upload_destination: sponsors_fs
            namer: vich_uploader.namer_origname

        sponsor_small_image:
            uri_prefix:         /images/sponsors
            upload_destination: sponsors_fs
            namer: wbb_uploader.namer_my_origname

        avatar_image:
            uri_prefix:         /images/avatars
            upload_destination: avatars_fs
            namer: vich_uploader.namer_origname
