imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS UserBundle config
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: WBB\UserBundle\Entity\User

sonata_admin:
    title:      "WBB - Administration"
    #title_logo: /bundles/wwbcore/images/common/logo.png
    dashboard:
        blocks:
            # display a dashboard block
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Bienvenue sur votre espace d'administration WBB</h2>
                        <p>Cette interface vous permet de mettre à jour le contenu du site WBB. <br />
                        Vous aurez la possibilité de gérer les utilisateurs,
                        les informations relatives aux bars, tips, et villes. </p><br /><br />
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            wbb_user: ~
            wbb_bar: ~
#    templates:
#        layout: SonataAdminBundle::base_admin.html.twig

# Sonata Admin bundle
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:

#Fake Data Generator
hautelook_alice:
    locale: fr_FR
    seed: 1