imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    SonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS UserBundle config
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: WBB\UserBundle\Entity\User

# Sonata Admin bundle
sonata_admin:
    title:      "WBB - Administration"
    security:
            handler: sonata.admin.security.handler.role
    #title_logo: /bundles/wwbcore/images/common/logo.png
    dashboard:
        blocks:
            # display a dashboard block
            -
                position: left
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Bienvenue sur votre espace d'administration WBB</h2>
                        <p>Cette interface vous permet de mettre à jour le contenu du site WBB. <br />
                        Vous aurez la possibilité de gérer les utilisateurs,
                        les informations relatives aux bars, tips, et villes. </p><br /><br />
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            wbb_user: ~
            wbb_bar: ~
            wbb_location: ~
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        layout: SonataAdminBundle::layout.html.twig
        short_object_description: WBBBarBundle:Admin:Helper/short-object-description.html.twig

# Sonata Blocks
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:

#Sonata Media Bundle
sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small:          { width: 100 , quality: 70}
                big:            { width: 500 , quality: 70}
                large:          { width: 1024, quality: 70}
                slider_small :  { width: 320 , height: 240, quality: 70 }
                slider_large :  { width: 640 , height: 480, quality: 70 }
    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        image:
            resizer: sonata.media.resizer.square

#Fake Data Generator
hautelook_alice:
    locale: fr_FR
    seed: 1

#Foursquare API Configuration
jcroll_foursquare_api:
    client_id:     %foursquare_client_id%
    client_secret: %foursquare_client_secret%

sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig #keep this commented unless you are using media bundle.
        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig
        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig
        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig
        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions

mobile_detect:
    redirect:
        mobile: {is_enabled: false}
        tablet: {is_enabled: false}
    switch_device_view:
        save_referer_path: true
    extension_class: WBB\CoreBundle\Twig\Extension\MobileDetectExtension