imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: bundles/services/services.yml }
    - { resource: bundles/fos.yml }
    - { resource: bundles/sonata.yml }
    - { resource: bundles/sonata_media.yml }
    - { resource: bundles/gaufrette.yml }
    - { resource: bundles/liip.yml }
    - { resource: bundles/vich.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true, enabled: true, api: 2.4 }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session: ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'StnwDatePickerBundle:Form:fields.html.twig'
    globals:
        feedsLimit: %feeds_limit%
        websiteUrl: %website_url%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    numeric_functions:
                        geo: WBB\CoreBundle\AST\Functions\Geo
                mappings:
                    SonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    #spool:     { type: memory }

#Fake Data Generator
hautelook_alice:
    locale: fr_FR
    seed: 1

#Foursquare API Configuration
jcroll_foursquare_api:
    client_id:     %foursquare_client_id%
    client_secret: %foursquare_client_secret%

mobile_detect:
    redirect:
        mobile: {is_enabled: false}
        tablet: {is_enabled: false}
    switch_device_view:
        save_referer_path: true
    extension_class: WBB\CoreBundle\Twig\Extension\MobileDetectExtension

#CreatedAt et UpdatedAt Extention
stof_doctrine_extensions:
   orm:
       default:
           timestampable: true
           sluggable:  true

fos_facebook:
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_app_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]

hpatoio_bitly:
    access_token: %bitly_access_token%
