wbb_bar:
    resource: "@WBBBarBundle/Resources/config/routing.yml"
    prefix:   /

wbb_core:
    resource: "@WBBCoreBundle/Resources/config/routing/routing.yml"
    prefix:   /

wbb_user:
    resource: "@WBBUserBundle/Resources/config/routing/routing.yml"
    prefix:   /

wbb_cloudsearch:
    resource: "@WBBCloudSearchBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_security_check:
    pattern:  /loginfb_check

_security_logout:
    pattern:  /logoutfb

_security_login:
    pattern: /loginfb
    defaults: { _controller: WBBUserBundle:Security:facebookLogin }

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"
