security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: sonata_admin_homepage
                always_use_default_target_path: true
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true

        main:
            pattern: ^/.*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

            # Secure Admin Dahsboard
            - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin(.*), role: [ROLE_SUPER_ADMIN] }


    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - WBB_BAR_ALL
            - WBB_CITY_ALL
        ROLE_MODERATOR:
            - ROLE_ADMIN
            - WBB_BAR_ALL
        ROLE_PUBLISHER:
            - ROLE_ADMIN
            - WBB_BAR_ALL
        ROLE_EDITORIAL_EXPERT:
        ROLE_BAR_EXPERT:
            - ROLE_ADMIN
            - WBB_BAR_ALL
        ROLE_BAR_OWNER:
            - ROLE_ADMIN
            - WBB_BAR_ALL
        ROLE_ADMIN:
            - ROLE_USER



        WBB_BAR_ALL:
            - ROLE_WBB_BAR_LIST
            - ROLE_WBB_BAR_VIEW
            - ROLE_WBB_BAR_CREATE
            - ROLE_WBB_BAR_EDIT
            - ROLE_WBB_BAR_DELETE
            
        WBB_CITY_ALL:
            - ROLE_WBB_BAR_LIST
            - ROLE_WBB_BAR_VIEW
            - ROLE_WBB_BAR_CREATE
            - ROLE_WBB_BAR_EDIT
            - ROLE_WBB_BAR_DELETE


