security:
    encoders:
        FOS\UserBundle\Model\UserInterface: {id: wbb_md5_password_encoder } #sha512

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        fos_facebook_provider:
            id: facebook.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: sonata_admin_homepage
                always_use_default_target_path: true
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true
            switch_user: true

        main:
            pattern: ^/.*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            switch_user: true
            fos_facebook:
                login_path: /loginfb
                check_path: _security_check
                provider: fos_facebook_provider

    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

            # Secure Admin Dahsboard
            - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin(.*), role: [ROLE_ADMIN] }

            #Ensecure the rest
            - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:

        #User Roles
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN

        ROLE_BAR_OWNER:
            - ROLE_ADMIN
            - ROLE_WBB_BAR_ALL
            - ROLE_WBB_BAR_MEDIA_ALL
            - ROLE_WBB_BAR_TAG_ALL
            - ROLE_WBB_BAR_FS_IMGS

        ROLE_BAR_EXPERT:
            - ROLE_ADMIN
            - ROLE_WBB_BAR_ALL
            - ROLE_WBB_BAR_MEDIA_ALL
            - ROLE_WBB_BAR_TAG_ALL
            - ROLE_WBB_BAR_FS_IMGS
            - ROLE_WBB_BESTOF_ALL

        ROLE_EDITORIAL_EXPERT:
            - ROLE_ADMIN
            - ROLE_WBB_BESTOF_ALL
            - ROLE_WBB_NEWS_ALL

        ROLE_PUBLISHER:
            - ROLE_ADMIN
            - ROLE_WBB_BAR_ALL
            - ROLE_WBB_BAR_MEDIA_ALL
            - ROLE_WBB_BAR_TAG_ALL
            - ROLE_BAR_ID
            - ROLE_WBB_BAR_FS_IMGS
            - ROLE_WBB_BAR_INSTAGRAM
            - ROLE_WBB_BESTOF_ALL
            - ROLE_WBB_TAG_ALL
            - ROLE_WBB_TIP_ALL
            - ROLE_WBB_NEWS_ALL
            - ROLE_WBB_AD_ALL

        ROLE_MODERATOR:
            - ROLE_ADMIN
            - ROLE_WBB_BAR_ALL
            - ROLE_WBB_BAR_MEDIA_ALL
            - ROLE_WBB_BAR_TAG_ALL
            - ROLE_WBB_BAR_FEED_ALL
            - ROLE_BAR_ID
            - ROLE_WBB_BESTOF_ALL
            - ROLE_WBB_TIP_ALL
            - ROLE_WBB_USERS_ALL

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_BAR_ID
            - ROLE_WBB_BAR_FEED_ALL
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_WBB_TAG_ALL

        # Roles attributs
        ROLE_WBB_BAR_ALL:
            - ROLE_WBB_BAR_ADMIN_BAR_LIST
            - ROLE_WBB_BAR_ADMIN_BAR_VIEW
            - ROLE_WBB_BAR_ADMIN_BAR_CREATE
            - ROLE_WBB_BAR_ADMIN_BAR_EDIT
            - ROLE_WBB_BAR_ADMIN_BAR_DELETE
            - ROLE_WBB_BAR_MEDIA_ALL
            - ROLE_WBB_BAR_TAG_ALL
            - ROLE_WBB_BAR_OPENING_ALL

        ROLE_WBB_BAR_FEED_ALL:
            - ROLE_WBB_BAR_FS_TIPS
            - ROLE_WBB_BAR_FS_IMGS
            - ROLE_WBB_BAR_INSTAGRAM

        ROLE_WBB_BAR_MEDIA_ALL:
            - ROLE_WBB_BAR_ADMIN_BAR_MEDIA_LIST
            - ROLE_WBB_BAR_ADMIN_BAR_MEDIA_VIEW
            - ROLE_WBB_BAR_ADMIN_BAR_MEDIA_CREATE
            - ROLE_WBB_BAR_ADMIN_BAR_MEDIA_EDIT
            - ROLE_WBB_BAR_ADMIN_BAR_MEDIA_DELETE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL

        ROLE_SONATA_MEDIA_ADMIN_MEDIA_ALL:
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_DELETE

        ROLE_WBB_BAR_TAG_ALL:
            - ROLE_WBB_BAR_ADMIN_BAR_TAG_LIST
            - ROLE_WBB_BAR_ADMIN_BAR_TAG_VIEW
            - ROLE_WBB_BAR_ADMIN_BAR_TAG_CREATE
            - ROLE_WBB_BAR_ADMIN_BAR_TAG_EDIT
            - ROLE_WBB_BAR_ADMIN_BAR_TAG_DELETE
            - ROLE_WBB_BAR_ADMIN_TAG_LIST

        ROLE_WBB_BAR_OPENING_ALL:
            - ROLE_WBB_BAR_ADMIN_BAR_OPENING_LIST
            - ROLE_WBB_BAR_ADMIN_BAR_OPENING_VIEW
            - ROLE_WBB_BAR_ADMIN_BAR_OPENING_CREATE
            - ROLE_WBB_BAR_ADMIN_BAR_OPENING_EDIT
            - ROLE_WBB_BAR_ADMIN_BAR_OPENING_DELETE

        ROLE_WBB_TAG_ALL:
            - ROLE_WBB_BAR_ADMIN_TAG_LIST
            - ROLE_WBB_BAR_ADMIN_TAG_VIEW
            - ROLE_WBB_BAR_ADMIN_TAG_CREATE
            - ROLE_WBB_BAR_ADMIN_TAG_EDIT
            - ROLE_WBB_BAR_ADMIN_TAG_DELETE

        ROLE_WBB_BESTOF_ALL:
            - ROLE_WBB_BAR_ADMIN_BESTOF_LIST
            - ROLE_WBB_BAR_ADMIN_BESTOF_VIEW
            - ROLE_WBB_BAR_ADMIN_BESTOF_CREATE
            - ROLE_WBB_BAR_ADMIN_BESTOF_EDIT
            - ROLE_WBB_BAR_ADMIN_BESTOF_DELETE
            - ROLE_WBB_BESTOF_TAG_ALL

        ROLE_WBB_BESTOF_TAG_ALL:
            - ROLE_WBB_BAR_ADMIN_BESTOF_TAG_LIST
            - ROLE_WBB_BAR_ADMIN_BESTOF_TAG_VIEW
            - ROLE_WBB_BAR_ADMIN_BESTOF_TAG_CREATE
            - ROLE_WBB_BAR_ADMIN_BESTOF_TAG_EDIT
            - ROLE_WBB_BAR_ADMIN_BESTOF_TAG_DELETE

        ROLE_WBB_TIP_ALL:
            - ROLE_WBB_BAR_ADMIN_TIP_LIST
            - ROLE_WBB_BAR_ADMIN_TIP_VIEW
            - ROLE_WBB_BAR_ADMIN_TIP_CREATE
            - ROLE_WBB_BAR_ADMIN_TIP_EDIT
            - ROLE_WBB_BAR_ADMIN_TIP_DELETE

        ROLE_WBB_AD_ALL:
            - ROLE_WBB_BAR_ADMIN_AD_LIST
            - ROLE_WBB_BAR_ADMIN_AD_VIEW
            - ROLE_WBB_BAR_ADMIN_AD_CREATE
            - ROLE_WBB_BAR_ADMIN_AD_EDIT
            - ROLE_WBB_BAR_ADMIN_AD_DELETE

        ROLE_WBB_NEWS_ALL:
            - ROLE_WBB_BAR_ADMIN_NEWS_LIST
            - ROLE_WBB_BAR_ADMIN_NEWS_VIEW
            - ROLE_WBB_BAR_ADMIN_NEWS_CREATE
            - ROLE_WBB_BAR_ADMIN_NEWS_EDIT
            - ROLE_WBB_BAR_ADMIN_NEWS_DELETE
            - ROLE_WBB_NEWS_MEDIA_ALL

        ROLE_WBB_NEWS_MEDIA_ALL:
            - ROLE_WBB_BAR_ADMIN_NEWS_MEDIA_LIST
            - ROLE_WBB_BAR_ADMIN_NEWS_MEDIA_VIEW
            - ROLE_WBB_BAR_ADMIN_NEWS_MEDIA_CREATE
            - ROLE_WBB_BAR_ADMIN_NEWS_MEDIA_EDIT
            - ROLE_WBB_BAR_ADMIN_NEWS_MEDIA_DELETE

        ROLE_WBB_USERS_ALL:
            - ROLE_WBB_USER_ADMIN_USER_LIST
            - ROLE_WBB_USER_ADMIN_USER_VIEW
            - ROLE_WBB_USER_ADMIN_USER_CREATE
            - ROLE_WBB_USER_ADMIN_USER_EDIT
            - ROLE_WBB_USER_ADMIN_USER_DELETE

        ROLE_LOCATION_ALL:
            - ROLE_WBB_COUNTRY_ALL
            - ROLE_WBB_CITY_ALL
            - ROLE_WBB_CITY_SUBURB_ALL

        ROLE_WBB_COUNTRY_ALL:
            - ROLE_WBB_CORE_ADMIN_COUNTRY_LIST
            - ROLE_WBB_CORE_ADMIN_COUNTRY_VIEW
            - ROLE_WBB_CORE_ADMIN_COUNTRY_CREATE
            - ROLE_WBB_CORE_ADMIN_COUNTRY_EDIT
            - ROLE_WBB_CORE_ADMIN_COUNTRY_DELETE

        ROLE_WBB_CITY_ALL:
            - ROLE_WBB_CORE_ADMIN_CITY_LIST
            - ROLE_WBB_CORE_ADMIN_CITY_VIEW
            - ROLE_WBB_CORE_ADMIN_CITY_CREATE
            - ROLE_WBB_CORE_ADMIN_CITY_EDIT
            - ROLE_WBB_CORE_ADMIN_CITY_DELETE
            - ROLE_WBB_CITY_TAG_ALL
            - ROLE_WBB_CITY_BESTOF_ALL

        ROLE_WBB_CITY_SUBURB_ALL:
            - ROLE_WBB_CORE_ADMIN_CITY_SUBURB_LIST
            - ROLE_WBB_CORE_ADMIN_CITY_SUBURB_VIEW
            - ROLE_WBB_CORE_ADMIN_CITY_SUBURB_CREATE
            - ROLE_WBB_CORE_ADMIN_CITY_SUBURB_EDIT
            - ROLE_WBB_CORE_ADMIN_CITY_SUBURB_DELETE

        ROLE_WBB_CITY_TAG_ALL:
            - ROLE_WBB_CORE_ADMIN_CITY_TAG_LIST
            - ROLE_WBB_CORE_ADMIN_CITY_TAG_VIEW
            - ROLE_WBB_CORE_ADMIN_CITY_TAG_CREATE
            - ROLE_WBB_CORE_ADMIN_CITY_TAG_EDIT
            - ROLE_WBB_CORE_ADMIN_CITY_TAG_DELETE

        ROLE_WBB_CITY_BESTOF_ALL:
            - ROLE_WBB_CORE_ADMIN_CITY_BESTOF_LIST
            - ROLE_WBB_CORE_ADMIN_CITY_BESTOF_VIEW
            - ROLE_WBB_CORE_ADMIN_CITY_BESTOF_CREATE
            - ROLE_WBB_CORE_ADMIN_CITY_BESTOF_EDIT
            - ROLE_WBB_CORE_ADMIN_CITY_BESTOF_DELETE