services:
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;dbname=%database_name%"
            - "%database_user%"
            - "%database_password%"
        calls:
            - [setAttribute, [3, 2]]

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]

    wbb.block.service.semsoft.import:
        class: WBB\CoreBundle\Block\ImportService
        arguments: [ "wbb.block.service.semsoft.import", @templating, @service_container ]
        tags:
         - { name: sonata.block }
