parameters:

    #Admin Classes
    wbb_user.user.admin.class: WBB\UserBundle\Controller\Admin\UserAdmin

    #Entities
    wbb_user.user.entity.class: WBB\UserBundle\Entity\User

services:

    #Admin Class
    wbb.user.admin.user:
        class: %wbb_user.user.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_user_hidden, label: users, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_user.user.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
            - [setTranslationDomain, ["WBBUserBundle"]]

    #User repository
    user.repository:
        class: WBB\UserBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBUserBundle:User']