parameters:

    #Admin Classes
    wbb_user.user.admin.class: WBB\UserBundle\Controller\Admin\UserAdmin

    #Entities
    wbb_user.user.entity.class: WBB\UserBundle\Entity\User

    #Password Encoder Class
    wbb_user.user.md5_password_encoder.class: WBB\UserBundle\Security\Password\Encoder\Md5Encoder

services:
    facebook.user:
        class: WBB\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"

    #Admin Class
    wbb.user.admin.user:
        class: %wbb_user.user.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_user, label: users, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_user.user.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
            - [setTranslationDomain, ["WBBUserBundle"]]
            - [setTemplates, [{ edit: "WBBUserBundle:Admin:User/edit.html.twig"}]]

    #User repository
    user.repository:
        class: WBB\UserBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBUserBundle:User']

    #User Registration Form
    wbb_user.registration.form.type:
        class: WBB\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wbb_user_registration }

    wbb_user.registration.light.form.type:
        class: WBB\UserBundle\Form\Type\RegistrationLightFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wbb_user_registration_light }

    wbb_user.profile.form.type:
            class: WBB\UserBundle\Form\Type\ProfileFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: wbb_user_profile }

    #FormFactory
    wbb_user.registration.form.factory:
        class: WBB\UserBundle\Form\Factory\FormFactory
        arguments: [@form.factory, %fos_user.registration.form.name%, %fos_user.registration.form.type%, %fos_user.registration.form.validation_groups% ]

    #MD5 password encoder
    wbb_md5_password_encoder:
        class: %wbb_user.user.md5_password_encoder.class%

    #Mailers
    wbb_user.generate_password.mailer:
        class:  WBB\UserBundle\Mailer\GeneratePasswordMailer
        parent: wbb_core.mailer.twig_swift
        public: true

    wbb_registration_succes_listener:
        class: WBB\UserBundle\EventListener\RegistrationListener
        arguments: ["@service_container"]
        tags:
            - { name: 'kernel.event_subscriber' }

    #Login Listener
    wbb_login_listener:
        class: 'WBB\UserBundle\EventListener\LoginListener'
        arguments: ['@security.context', '@doctrine', '@service_container']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    wbb.logout.success_handler:
        class: WBB\UserBundle\Security\Authentication\LogoutSuccessHandler
        arguments: ["@router"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }