parameters:

    #Admin Classes
    wbb_user.user.admin.class: WBB\UserBundle\Controller\Admin\UserAdmin

    #Entities
    wbb_user.user.entity.class: WBB\UserBundle\Entity\User

services:

    #Admin Class
    wbb.user.admin.user:
        class: %wbb_user.user.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_user, label: users, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_user.user.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
            - [setTranslationDomain, ["WBBUserBundle"]]
            - [setTemplates, [{ edit: "WBBUserBundle:Admin:User/edit.html.twig"}]]

    #User repository
    user.repository:
        class: WBB\UserBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBUserBundle:User']

    #User Registration Form
    wbb_user.registration.form.type:
        class: WBB\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: wbb_user_registration }