#FOS\UserBundle\Form\Model\ChangePassword:
#    properties:
#        current:
#            - NotBlank: { message: "3emerni", groups: [ChangePassword, Default]}

#FOS\UserBundle\Form\Model\ChangePassword:
#    properties:
#        new:
#            - Length: { min: 6, minMessage: "wa zid mazal", groups: [ChangePassword] }