FOS\UserBundle\Model\User:
    properties:
        password:
            - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
                message: "The entered password is invalid."