wbb_bar_test:
    pattern:  /feed/fsTips/{venue}
    defaults: { _controller: WBBBarBundle:FSAdmin:testFS }
    options:
            expose: true

wbb_bar_feeds_find:
    pattern:  /feed/find/{type}/{id}
    defaults: { _controller: WBBBarBundle:FSAdmin:find }
    options:
            expose: true

wbb_bar_feeds_list:
    pattern:  /feed/list/{type}/{bar}
    defaults: { _controller: WBBBarBundle:FSAdmin:list }
    options:
            expose: true

wbb_bar_feed_add:
    pattern:  /feed/save/{type}/{hash}/{bar}
    defaults: { _controller: WBBBarBundle:FSAdmin:add }
    options:
            expose: true
            
wbb_bar_feed_remove:
    pattern:  /feed/remove/{type}/{hash}/{bar}
    defaults: { _controller: WBBBarBundle:FSAdmin:remove }
    options:
            expose: true