parameters:

    #Admin Classes
    wbb_bar.bar.admin.class: WBB\BarBundle\Controller\Admin\BarAdmin
    wbb_bar.bar_media.admin.class: WBB\BarBundle\Controller\Admin\Collections\BarMediaAdmin
    wbb_bar.bar_trend.admin.class: WBB\BarBundle\Controller\Admin\Collections\BarTrendAdmin
    wbb_bar.bar_opening.admin.class: WBB\BarBundle\Controller\Admin\BarOpeningAdmin
    wbb_bar.trend.admin.class: WBB\BarBundle\Controller\Admin\TrendAdmin
    wbb_bar.bestof.admin.class: WBB\BarBundle\Controller\Admin\BestOfAdmin
    wbb_bar.bestof_trend.admin.class: WBB\BarBundle\Controller\Admin\Collections\BestofTrendAdmin
    wbb_bar.tip.admin.class: WBB\BarBundle\Controller\Admin\TipAdmin
    wbb_bar.ad.admin.class: WBB\BarBundle\Controller\Admin\AdAdmin
    wbb_bar.news.admin.class: WBB\BarBundle\Controller\Admin\NewsAdmin
    wbb_bar.news_media.admin.class: WBB\BarBundle\Controller\Admin\Collections\NewsMediaAdmin

    #Entities
    wbb_bar.bar.entity.class: WBB\BarBundle\Entity\Bar
    wbb_bar.bar_media.entity.class: WBB\BarBundle\Entity\Collections\BarMedia
    wbb_bar.bar_trend.entity.class: WBB\BarBundle\Entity\Collections\BarTrend
    wbb_bar.bar_opening.entity.class: WBB\BarBundle\Entity\BarOpening
    wbb_bar.trend.entity.class: WBB\BarBundle\Entity\Trend
    wbb_bar.bestof.entity.class: WBB\BarBundle\Entity\BestOf
    wbb_bar.bestof_trend.entity.class: WBB\BarBundle\Entity\Collections\BestofTrend
    wbb_bar.tip.entity.class: WBB\BarBundle\Entity\Tip
    wbb_bar.ad.entity.class: WBB\BarBundle\Entity\Ad
    wbb_bar.news.entity.class: WBB\BarBundle\Entity\News
    wbb_bar.news_media.entity.class: WBB\BarBundle\Entity\Collections\NewsMedia

    #Feed Classes
    wbb_feed.foursquare_tips.class: WBB\BarBundle\Feed\FoursquareTips
    wbb_feed.foursquare_imgs.class: WBB\BarBundle\Feed\FoursquareImgs
    wbb_feed.instagram.class: WBB\BarBundle\Feed\Instagram

services:

    #Admin Class
    wbb.bar.admin.bar:
        class: %wbb_bar.bar.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: bars, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]
            - [setTemplates, [{ edit:"WBBBarBundle:Admin:Bar/edit.html.twig" }]]

    wbb.bar.admin.bar_media:
        class: %wbb_bar.bar_media.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: medias, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar_media.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bar_trend:
        class: %wbb_bar.bar_trend.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: bar_trends, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar_trend.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bar_opening:
        class: %wbb_bar.bar_opening.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: openings, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar_opening.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.trend:
        class: %wbb_bar.trend.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: trends, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.trend.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bestof:
        class: %wbb_bar.bestof.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: bestofs, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bestof.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bestof_trend:
        class: %wbb_bar.bestof_trend.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: bestof_trend, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bestof_trend.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.tip:
        class: %wbb_bar.tip.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: tips, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.tip.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.ad:
        class: %wbb_bar.ad.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: ad, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.ad.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.news:
        class: %wbb_bar.news.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: news, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.news.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.news_media:
        class: %wbb_bar.news_media.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: news_medias, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.news_media.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    # Feed
    wbb.fstips.feed:
        class: %wbb_feed.foursquare_tips.class%
        arguments: [ @service_container, @doctrine.orm.entity_manager, %feeds_limit% ]

    wbb.fsimgs.feed:
        class: %wbb_feed.foursquare_imgs.class%
        arguments: [ @service_container, @doctrine.orm.entity_manager, %feeds_limit% ]

    wbb.instagram.feed:
        class: %wbb_feed.instagram.class%
        arguments: [ @service_container, @doctrine.orm.entity_manager, %feeds_limit% , %instagram_client_id%]

    #Repositories
    bar.repository:
        class: WBB\BarBundle\Repository\BarRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:Bar']