parameters:

    #Admin Classes
    wbb_bar.bar.admin.class: WBB\BarBundle\Controller\Admin\BarAdmin
    wbb_bar.semsoftbar.admin.class: WBB\BarBundle\Controller\Admin\SemsoftBarAdmin
    wbb_bar.bar_media.admin.class: WBB\BarBundle\Controller\Admin\Collections\BarMediaAdmin
    wbb_bar.bar_tag.admin.class: WBB\BarBundle\Controller\Admin\Collections\BarTagAdmin
    wbb_bar.bar_opening.admin.class: WBB\BarBundle\Controller\Admin\BarOpeningAdmin
    wbb_bar.tag.admin.class: WBB\BarBundle\Controller\Admin\TagAdmin
    wbb_bar.bestof.admin.class: WBB\BarBundle\Controller\Admin\BestOfAdmin
    wbb_bar.bestof_tag.admin.class: WBB\BarBundle\Controller\Admin\Collections\BestOfTagAdmin
    wbb_bar.bestof_bar.admin.class: WBB\BarBundle\Controller\Admin\Collections\BestOfBarAdmin
    wbb_bar.tip.admin.class: WBB\BarBundle\Controller\Admin\TipAdmin
    wbb_bar.ad.admin.class: WBB\BarBundle\Controller\Admin\AdAdmin
    wbb_bar.news.admin.class: WBB\BarBundle\Controller\Admin\NewsAdmin
    wbb_bar.news_media.admin.class: WBB\BarBundle\Controller\Admin\Collections\NewsMediaAdmin

    #CRUD Controllers
    wbb_bar.tip.crud.class: WBBBarBundle:CRUD\TipCRUD
    wbb_bar.semsoft.crud.class: WBBBarBundle:CRUD\SemsoftCRUD

    #Entities
    wbb_bar.bar.entity.class: WBB\BarBundle\Entity\Bar
    wbb_bar.semsoftbar.entity.class: WBB\BarBundle\Entity\Semsoft\SemsoftBar
    wbb_bar.bar_media.entity.class: WBB\BarBundle\Entity\Collections\BarMedia
    wbb_bar.bar_tag.entity.class: WBB\BarBundle\Entity\Collections\BarTag
    wbb_bar.bar_opening.entity.class: WBB\BarBundle\Entity\BarOpening
    wbb_bar.tag.entity.class: WBB\BarBundle\Entity\Tag
    wbb_bar.bestof.entity.class: WBB\BarBundle\Entity\BestOf
    wbb_bar.bestof_tag.entity.class: WBB\BarBundle\Entity\Collections\BestOfTag
    wbb_bar.bestof_bar.entity.class: WBB\BarBundle\Entity\Collections\BestOfBar
    wbb_bar.tip.entity.class: WBB\BarBundle\Entity\Tip
    wbb_bar.ad.entity.class: WBB\BarBundle\Entity\Ad
    wbb_bar.news.entity.class: WBB\BarBundle\Entity\News
    wbb_bar.news_media.entity.class: WBB\BarBundle\Entity\Collections\NewsMedia

    #Feed Classes
    wbb_feed.foursquare_tips.class: WBB\BarBundle\Feed\FoursquareTips
    wbb_feed.foursquare_imgs.class: WBB\BarBundle\Feed\FoursquareImgs
    wbb_feed.instagram.class: WBB\BarBundle\Feed\Instagram

services:
    #Blocks
    wbb.block.service.semsoft.import:
        class: WBB\BarBundle\Block\ImportService
        arguments: [ "wbb.block.service.semsoft.import", @templating, @service_container ]
        tags:
         - { name: sonata.block }

    #Admin Class
    wbb.bar.admin.bar:
        class: %wbb_bar.bar.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: bars, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar.entity.class%, %wbb_bar.semsoft.crud.class%]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]
            - [setTemplates, [{ edit: "WBBBarBundle:Admin:Bar/edit.html.twig", list: "WBBBarBundle:Admin:Bar/list.html.twig" }]]

    wbb.semsoftbar.admin.bar:
        class: %wbb_bar.semsoftbar.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: semsoft_bars, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.semsoftbar.entity.class%, %wbb_bar.semsoft.crud.class%]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]
            - [setTemplates, [{ edit: "WBBBarBundle:Admin:Semsoft/edit.html.twig" }]]

    wbb.bar.admin.bar.media:
        class: %wbb_bar.bar_media.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: medias, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar_media.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bar.tag:
        class: %wbb_bar.bar_tag.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: bar_tags, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar_tag.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bar.opening:
        class: %wbb_bar.bar_opening.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: openings, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bar_opening.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bestof:
        class: %wbb_bar.bestof.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: bestofs, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bestof.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]
            - [setTemplates, [{ edit:"WBBBarBundle:Admin:BestOf/edit.html.twig" }]]

    wbb.bar.admin.bestof.tag:
        class: %wbb_bar.bestof_tag.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: bestof_tag, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bestof_tag.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.bestof.bar:
        class: %wbb_bar.bestof_bar.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: bestof_bar, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.bestof_bar.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.tag:
        class: %wbb_bar.tag.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: tags, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.tag.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.tip:
        class: %wbb_bar.tip.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: tips, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.tip.entity.class%, %wbb_bar.tip.crud.class%]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]
            - [setTemplates, [{ edit:"WBBBarBundle:Admin:Tip/edit.html.twig" }]]
            - [setTemplates, [{ list:"WBBBarBundle:Admin:Tip/list.html.twig" }]]

    wbb.bar.admin.news:
        class: %wbb_bar.news.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: news, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.news.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.news.media:
        class: %wbb_bar.news_media.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar_hidden, label: news_medias, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.news_media.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    wbb.bar.admin.ad:
        class: %wbb_bar.ad.admin.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: wbb_bar, label: ad, label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %wbb_bar.ad.entity.class%, SonataAdminBundle:CRUD]
        calls:
            - [setTranslationDomain, ["WBBBarBundle"]]

    # Feed
    wbb.fstips.feed:
        class: %wbb_feed.foursquare_tips.class%
        arguments: [ @service_container, @doctrine.orm.entity_manager, %feeds_limit% ]

    wbb.fsimgs.feed:
        class: %wbb_feed.foursquare_imgs.class%
        arguments: [ @service_container, @doctrine.orm.entity_manager, %feeds_limit% ]

    wbb.instagram.feed:
        class: %wbb_feed.instagram.class%
        arguments: [ @doctrine.orm.entity_manager, %feeds_limit% , %instagram_client_id%]

    #Repositories
    bar.repository:
        class: WBB\BarBundle\Repository\BarRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:Bar']

    bestof.repository:
        class: WBB\BarBundle\Repository\BestOfRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:BestOf']

    news.repository:
        class: WBB\BarBundle\Repository\NewsRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:News']

    ad.repository:
        class: WBB\BarBundle\Repository\AdRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:Ad']

    tip.repository:
        class: WBB\BarBundle\Repository\TipRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:Tip']

    tag.repository:
        class: WBB\BarBundle\Repository\TagRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:Tag']

    bar.tag.repository:
        class: WBB\BarBundle\Repository\BarTagRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['WBBBarBundle:Collections\BarTag']

    #Resizer
    sonata.media.resizer.custom:
        class: WBB\BarBundle\Resizer\CustomResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]

    wbb.twig.favorite_extension:
        class: WBB\BarBundle\Twig\Extension\FavoriteExtension
        arguments:
            - "@router"
        tags:
            - { name: twig.extension }

    wbb.tips.event_listener:
        class: WBB\BarBundle\EventListener\TipsListener
        arguments:
            - "@service_container"
            - "@swiftmailer.mailer.default"
            - "@router"
            - "@twig"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }

    wbb.mailer:
        class: WBB\BarBundle\Mailer\TipsMailer

    #Bar Persist Listener
    wbb.bar.listener:
        class: WBB\BarBundle\EventListener\BarListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }

    wbb.request.listener:
        class: WBB\BarBundle\EventListener\ControllerListener
        arguments: ["@wbb.favorites_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    wbb.favorites_manager:
        class: WBB\BarBundle\Manager\FavoritesManager
        calls:
            - [setContainer, ["@service_container"]]

    # Share Mail Service
    wbb_bar.share.mailer:
        class:  WBB\BarBundle\Mailer\ShareMailer
        parent: wbb_core.mailer.twig_swift
        public: true
