services:
    cloudsearch.indexer:
        class: WBB\CloudSearchBundle\Indexer\CloudSearchIndexer
        arguments:
            - "@service_container"
            -
                - "%aws_cloudsearch_domain_name%"
                - "%aws_cloudsearch_domain_id%"
                - "%aws_cloudsearch_region%"
                - "%aws_cloudsearch_key%"
                - "%aws_cloudsearch_secret%"

    cloudsearch.searcher:
        class: WBB\CloudSearchBundle\Searcher\CloudSearchSearcher
        arguments:
            - "@service_container"
            -
                - "%aws_cloudsearch_domain_name%"
                - "%aws_cloudsearch_domain_id%"
                - "%aws_cloudsearch_region%"
                - "%aws_cloudsearch_key%"
                - "%aws_cloudsearch_secret%"

#    cloudsearch.indexer.listener:
#        class: WBB\CloudSearchBundle\EventListener\CloudSearchIndexerListener
#        arguments: ['@cloudsearch.indexer']
#        tags:
#            - { name: doctrine.event_listener, event: postPersist }
#            - { name: doctrine.event_listener, event: postUpdate }
#            - { name: doctrine.event_listener, event: preRemove }
