fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_registration_register:
    pattern: /register
    defaults: { _controller:FOSUserBundle:Registration:register }
    options:
        expose: true

wbb_user_registration_register_light:
    pattern: /register/light
    defaults: { _controller:WBBUserBundle:Registration:registerLight }
    options:
        expose: true

fos_user_registration_check_email:
    pattern: /register/check-email
    defaults: { _controller:FOSUserBundle:Registration:checkEmail }
    requirements:
        _method: GET

fos_user_registration_confirm:
    pattern: /register/confirm/{token}
    defaults: { _controller:FOSUserBundle:Registration:confirm }
    requirements:
        _method: GET

fos_user_registration_confirmed:
    pattern: /register/confirmed
    defaults: { _controller:FOSUserBundle:Registration:confirmed }
    requirements:
        _method: GET

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile