wbb_fos_user:
    resource: "@WBBUserBundle/Resources/config/routing/fosuser.yml"
    prefix:   /

wbb_user_favoris_add:
    pattern:  /favoris/add
    defaults: { _controller: WBBBarBundle:Favoris:add }
    
wbb_user_ajax_cities:
    pattern: /ajax/cities
    defaults: { _controller: WBBUserBundle:Ajax:cities }